apiVersion: v1
kind: Namespace
metadata:
  name: choreography
---
apiVersion: v1
kind: Service
metadata:
  name: shipment-app
  namespace: choreography
spec:
  selector:
    app: shipment-app
  ports:
  - port: 8080
    name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shipment-ingress
  namespace: choreography
spec:
  ingressClassName: nginx
  rules:
    - host: shipment-service.com
      http:
        paths:
          - path: /api/v1/shipment
            pathType: Prefix
            backend:
              service:
                name: shipment-app
                port:
                  number: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipment-app
  namespace: choreography
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipment-app
  template:
    metadata:
      labels:
        app: shipment-app
    spec:
      containers:
      - name: shipment-app
        image: 211125719632.dkr.ecr.eu-central-1.amazonaws.com/saga-choreography/shipment:4344a56
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            cpu: 250m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 120
          failureThreshold: 10
          timeoutSeconds: 5
          periodSeconds: 3
        env:
          - name: POSTGRES_URL
            value: "db-instance-choreography.chc66iy8gi9u.eu-central-1.rds.amazonaws.com:5432/shipment"
          - name: POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: dbpass
                key: db-pass
          - name: KAFKA_BROKER
            value: "b-1.choreographymsk.jaquu7.c8.kafka.eu-central-1.amazonaws.com:9092"
---
apiVersion: v1
kind: Secret
metadata:
  name: dbpass
  namespace: choreography
type: Opaque
data:
  db-pass: "cm9vdF9wb3N0Z3Jlc19wYXNz"